name: npm-install-with-retries
description: 'wraps npm install with retries/timeout to handle network failures'
inputs:
  ignore-scripts:
    default: 'false'
    description: 'Skip pre/post install scripts'
runs:
  using: composite
  steps:
    - name: npm install
      uses: salesforcecli/github-workflows/.github/actions/retry@main
      with:
        command: npm install --timeout 600000 ${{ inputs.ignore-scripts == 'true' && '--ignore-scripts' || '' }}
