name: npm-install-with-retries
description: 'wraps npm install with retries/timeout to handle network failures'
inputs:
  ignore-scripts:
    default: 'false'
    description: 'Skip pre/post install scripts'
runs:
  using: composite
  steps:
    - name: timeout config
      run: npm config set fetch-timeout 600000
      shell: bash
    - name: npm ci
      uses: salesforcecli/github-workflows/.github/actions/retry@main
      with:
        command: npm ci --no-audit --no-fund ${{ inputs.ignore-scripts == 'true' && '--ignore-scripts' || '' }}
