name: get prerelease tag
description: read package.json and return the version suffix (ex 'beta' if x.y.z-beta.0)

outputs:
  tag:
    value: ${{ steps.parsed.outputs.prerelease }}
    description: version suffix (ex 'beta' if x.y.z-beta.0 ), if exists in package.json
  version:
    value: ${{ steps.package-version.outputs.prop }}
    description: version from pjson

runs:
  using: composite
  steps:
    - uses: salesforcecli/github-workflows/.github/actions/get-json-property@main
      id: package-version
      with:
        path: "package.json"
        prop_path: "version"

    - name: Echo found version
      shell: bash
      run: echo "[INFO] Version found:\ $STEPS_PACKAGE_VERSION_PROP"
      env:
        STEPS_PACKAGE_VERSION_PROP: ${{ steps.package-version.outputs.prop }}

    - name: Parse semver version
      uses: salesforcecli/github-workflows/.github/actions/parse-semver@main
      id: parsed
      with:
        input_string: ${{ steps.package-version.outputs.prop }}

    - name: Echo found prerelease tag
      shell: bash
      run: echo "[INFO] Prerelease tag is:\ $STEPS_PARSED_PRERELEASE"
      env:
        STEPS_PARSED_PRERELEASE: ${{ steps.parsed.outputs.prerelease }}
