name: Determine node versions
description: "Get all the supported node versions"
inputs:
  nodeVersionOverride:
    description: Set node to a specific Semver version
    required: false
  nodeDisableVersions:
    description: A string of major version(s) to disable (18 or 18,23)
    required: false
outputs:
  nodeVersions:
    description: Node versions to be consumed by a workflow matrix
    value: ${{ steps.node-versions.outputs.nodeVersions }}
runs:
  using: 'composite'
  steps:
    # Note: this is not typically how you would run javascript in an action
    # This is need so that we can get the correct node version used elsewhere
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.nodeVersionOverride || 'lts/*' }}
    - name: Run main script
      shell: bash
      id: node-versions
      run: node "$GITHUB_ACTION_PATH/dist/index.js"
      env:
        NODE_DISABLE_VERSIONS: ${{ inputs.nodeDisableVersions }}

