name: jf-gha-exp.yml
on:
  workflow_call:
    inputs:
      pr_number:
        description: The number of the pull request to operate on
        required: true
        type: number

jobs:
  read-comments:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add a comment to the PR
        uses: actions/github-script@v7
        env:
          PR_NUMBER: ${{ inputs.pr_number }}
        with:
          script: |
            const comments = await github.paginate(github.rest.issues.listComments, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: Number(process.env.PR_NUMBER)
            });
            console.log(`COMMENT COUNT IS ${comments.length}`);
            const filterFn = (comment) => {
              return comment.user.type === "Bot"
                && comment.body === "Comment added by a machine! Beep boop!"
                && comment.reactions.eyes > 0
            };
            const commentsAcknowledgedByUser = comments.filter(filterFn);
            console.log(`NUMBER OF FILTER COMMENTS IS ${commentsAcknowledgedByUser.length}`);
            console.log(JSON.stringify(commentsAcknowledgedByUser, null, 2));
