on: workflow_call

jobs:
  pr-validation:
    if: ${{ !contains(github.event.pull_request.body, '[skip-validate-pr]') && !contains(github.event.pull_request.title, '[skip-validate-pr]') }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Validate Pull Request Title
        uses: kaisugi/action-regex-match@45cc5bacf016a4c0d2c3c9d0f8b7c2f1b79687b8
        id: regex-match-pr-title
        with:
          text: ${{ github.event.pull_request.title }}
          regex: '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)\s?(\(.+\))?: .+ \(W-\d{7,}\)$'
          flags: gmi

      - name: Validate Pull Request Body
        uses: kaisugi/action-regex-match@45cc5bacf016a4c0d2c3c9d0f8b7c2f1b79687b8
        id: regex-match-pr-body
        with:
          text: ${{ github.event.pull_request.body }}
          regex: '@W-\d{7,}@'
          flags: gmi

      # Disabling GHA Run and Github Issue (for now) due to E360 lookup

      # - name: Find Github Action Run
      #   uses: kaisugi/action-regex-match@45cc5bacf016a4c0d2c3c9d0f8b7c2f1b79687b8
      #   id: regex-match-gha-run
      #   with:
      #     text: ${{ github.event.pull_request.body }}
      #     regex: 'https:\/\/github\.com\/[\w\.-]+\/[\w\.-]+\/actions\/runs\/'
      #     flags: gm

      # - name: Find CLI Github Issue
      #   uses: kaisugi/action-regex-match@45cc5bacf016a4c0d2c3c9d0f8b7c2f1b79687b8
      #   id: regex-match-cli-gh-issue
      #   with:
      #     text: ${{ github.event.pull_request.body }}
      #     regex: 'forcedotcom\/cli\/issues\/[0-9]+|forcedotcom\/salesforcedx-vscode\/issues\/[0-9]+'
      #     flags: gm

      - name: Fail if format requirements not met
        if: |
          github.event.pull_request.user.login != 'dependabot[bot]' &&
          (github.event.pull_request.user.login != 'SF-CLI-BOT' || github.event.pull_request.user.login != 'svc-cli-bot') &&
          (steps.regex-match-pr-title.outputs.match == '' || steps.regex-match-pr-body.outputs.match == '')
        env:
          TITLE_MATCH: ${{
        run: |
          [[ '${{ steps.regex-match-pr-title.outputs.match }}' == '' ]] && TITLE_STATE=$'\u2714' || TITLE_STATE=$'\u2715'
          [[ '${{ steps.regex-match-pr-body.outputs.match }}' == '' ]] && BODY_STATE=$'\u2714' || BODY_STATE=$'\u2715'
          echo "::warning::PR titles and bodies must meet the specified criteria.
          - [$TITLE_STATE] PR title should be of format '<type>(<optional-scope>): <description> (W-XXXXXXX)'
            where <type> is one of: feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert
            e.g., feat: add Angular template support (W-12345678); fix(auth): resolve token refresh issue (W-12345679)
          - [$BODY_STATE] PR body must include a Work Item wrapped in @'s, ex: @W-12345678@ or [@W-12345678@](https://some-url)
          exit 1
